# Generated by Django 4.0.10 on 2023-04-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blooddonation_age_blooddonation_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='user.bloodrequest'),
        ),
    ]
