# Generated by Django 4.0.10 on 2023-04-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blooddonation_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
